"""集中所有的常量值"""

""" 用户相关 """
USER_ROLE_ADMIN = 0
USER_ROLE_CUSTOM = 1
USER_ROLE_ADMIN_TEXT = '管理员'
USER_ROLE_CUSTOM_TEXT = '普通用户'

USER_STATUS_FREEZE = 0
USER_STATUS_NORMAL = 1
USER_STATUS_FREEZE_TEXT = '冻结'
USER_STATUS_NORMAL_TEXT = '正常'


""" 菜品相关 """
FOOD_STATUS_DOWN = 0
FOOD_STATUS_UP = 1
FOOD_STATUS_DOWN_TEXT = '已下架'
FOOD_STATUS_UP_TEXT = '上架中'


""" 订单相关 """
# 未支付
ORDER_STATUS_UNPAID = 0
ORDER_STATUS_UNPAID_TEXT = '未支付'
# 已支付
ORDER_STATUS_PAID = 1
ORDER_STATUS_PAID_TEXT = '已支付'
# 已发货
ORDER_STATUS_SHIPPED = 2
ORDER_STATUS_SHIPPED_TEXT = '已发货'
# 待签收
ORDER_STATUS_PENDING_RECEIPT = 3
ORDER_STATUS_PENDING_RECEIPT_TEXT = '待签收'
# 已签收
ORDER_STATUS_RECEIVED = 4
ORDER_STATUS_RECEIVED_TEXT = '已签收'
# 退款中
ORDER_STATUS_REFUNDING = 5
ORDER_STATUS_REFUNDING_TEXT = '退款中'
# 已退款
ORDER_STATUS_REFUNDED = 6
ORDER_STATUS_REFUNDED_TEXT = '已退款'
# 退款失败
ORDER_STATUS_REFUND_FAILED = 7
ORDER_STATUS_REFUND_FAILED_TEXT = '退款失败'


""" 退款申请相关 """
# 未审核
REVIEW_STATUS_UNCHECKED = 0
REVIEW_STATUS_UNCHECKED_TEXT = "未审核"
# 审核通过
REVIEW_STATUS_CHECKED_SUCCESS = 1
REVIEW_STATUS_CHECKED_SUCCESS_TEXT = "审核通过"
# 审核失败
REVIEW_STATUS_CHECKED_FAILED = 2
REVIEW_STATUS_CHECKED_FAILED_TEXT = "审核失败"


